### ISSUE TITLE
Error when selecting Strategizer and still didn't create the team.

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/StrategizerClientModule#3]
Cannot read property 'fb' of undefined. Is the error on the browser console.

**Comment by Luis-Fernando-Molina** [comment]
same to me:

![image](https://user-images.githubusercontent.com/9479367/56689965-975fff80-66dc-11e9-845f-97b6d25d159c.png)

**Comment by bearcanrun** [comment]
Fixed in 0.0.14
